# syntax=docker/dockerfile:1
FROM python:3.7.3-stretch
RUN pip install --upgrade pip
WORKDIR /webinterface/
COPY webinterface/requirements.txt requirements.txt
RUN pip3 install tensorflow tensorflow-gpu
RUN pip install -r requirements.txt
COPY webinterface .
COPY resources ../resources
CMD ["python3", "webserver.py"]